# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa08250c565728e7ba96ec3671aba653a83118b17b947978d1e939baa705c3a59b06ee4a8f7f6a476d40f844956758884cb357bde4e840bd9daebccfa6e957a8

test:
  secret_key_base: 6317ec6a12dd3b04bbcfb6947c35c82d0c3318f14181cc1d6517b1e0df8a0611e2bcbfd751099423f27f1f678987a03e549708afb34dfd98357098d94c3da97f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
